### ISSUE TITLE
input constantly deleted

### ISSUE THREAD

**Issue by CPWeaver** [ardagnir/athame#23] opened 2015-09-22 18:24 UTC
Trying to get this running on debian and I'm seeing some odd behavior. When I'm in insert mode, anything I type is deleted after a small delay. So I type some characters, they disappear. Type some more, disappears again. I put a blank .athamerc and .bashrc in my home directory to no avail.

One other data point, I did have to do an ldconfig to add /usr/lib to my linker path to get bash to link properly after installing. I didn't see that in your docs anywhere so maybe I've misconfigured it somehow? I have vim 7.4 patches 1-873 and bash 4.3.42. Thanks!

**Comment by ardagnir** [comment] 2015-11-03 04:11
Thanks, I finally reproduced this bug. It looks like it is triggered by running athame with vim that has both patch 866 and was compiled with gui support.

I'll work on a fix.

**Comment by ardagnir** [comment] 2015-11-04 02:01
Fixed in 0.4 branch. I'll close this bug once I merge it into master.

**Closed** 2015-11-05 02:16 UTC

**Comment by CPWeaver** [comment] 2015-11-09 17:01
Awesome, thanks! Looking forward to trying it out again.
