### ISSUE TITLE
Dont install on my home (Debian Sid)

### ISSUE THREAD

**Issue by i5513** [ardagnir/athame#56] opened 2018-06-10 22:16 UTC
Hello,

I'm trying to test athame, but it did not work on my environment (Debian Sid)
See the log, how can I fix it?

Thank  you !

Log:
$ rm -rf athame/ local/
$ git clone --recursive http://github.com/ardagnir/athame
Clonando en 'athame'...
warning: redirigiendo a https://github.com/ardagnir/athame/
remote: Counting objects: 1490, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 1490 (delta 18), reused 12 (delta 6), pack-reused 1457
Recibiendo objetos: 100% (1490/1490), 2.84 MiB | 3.24 MiB/s, listo.
Resolviendo deltas: 100% (903/903), listo.
Submódulo 'vimbed' (http://github.com/ardagnir/vimbed) registrado para ruta 'vimbed'
Clonando en '/home/javi/athame/vimbed'...
warning: redirigiendo a https://github.com/ardagnir/vimbed/
remote: Counting objects: 237, done.        
remote: Total 237 (delta 0), reused 0 (delta 0), pack-reused 237        
Recibiendo objetos: 100% (237/237), 62.66 KiB | 408.00 KiB/s, listo.
Resolviendo deltas: 100% (94/94), listo.
Ruta de submódulo 'vimbed': check out realizado a '61f3ec7a7c4b27c2e554358db63cc45e3ed4854a'
~$ cd athame
~/athame$ mkdir -p ~/local
~/athame$ ./readline_athame_setup.sh --prefix=$HOME/local/ 2>&1 | tee install.log

[install.log](https://github.com/ardagnir/athame/files/2088272/install.log)

**Comment by ardagnir** [comment] 2018-06-10 22:41
Thanks for reporting this. There was a bug in the testing script, but it should be fixed now in master branch.

**Comment by i5513** [comment] 2018-06-11 21:59
Thank you very much,

Today it worked, but still a error is in the script , see:

```
Testing Athame Bash Shell without X...
Test 1:
speed=56
Success!

Installing Readline with Athame...
/bin/sh ./support/mkinstalldirs /home/javi/local/include \
	/home/javi/local/include/readline /home/javi/local/lib \
	/home/javi/local/share/info /home/javi/local/share/man/man3 /home/javi/local/share/doc/readline
mkdir -p -- /home/javi/local/include /home/javi/local/include/readline /home/javi/local/lib /home/javi/local/share/info /home/javi/local/share/man/man3 /home/javi/local/share/doc/readline
for f in readline.h chardefs.h keymaps.h history.h tilde.h rlstdc.h rlconf.h rltypedefs.h athame.h; do \
	/usr/bin/install -c -m 644 ./$f /home/javi/local/include/readline ; \
done
/usr/bin/install -c -m 644 ./CHANGES ./INSTALL ./README /home/javi/local/share/doc/readline
( if test -d doc ; then \
	cd doc && \
	make  infodir=/home/javi/local/share/info DESTDIR= install; \
  fi )
make[1]: se entra en el directorio '/home/javi/athame/readline-7.0_tmp/doc'
/bin/sh ../support/mkdirs /home/javi/local/share/info /home/javi/local/share/man/man3
if test -n "" ; then \
	/bin/sh ../support/mkdirs  ; \
fi
if test -f readline.info; then \
	/usr/bin/install -c -m 644 readline.info /home/javi/local/share/info/readline.info; \
else \
	/usr/bin/install -c -m 644 ./readline.info /home/javi/local/share/info/readline.info; \
fi
if test -f rluserman.info; then \
	/usr/bin/install -c -m 644 rluserman.info /home/javi/local/share/info/rluserman.info; \
else \
	/usr/bin/install -c -m 644 ./rluserman.info /home/javi/local/share/info/rluserman.info; \
fi
if test -f history.info; then \
	/usr/bin/install -c -m 644 history.info /home/javi/local/share/info/history.info; \
else \
	/usr/bin/install -c -m 644 ./history.info /home/javi/local/share/info/history.info; \
fi
if /bin/sh -c 'install-info --version' >/dev/null 2>&1; then \
	install-info --dir-file=/home/javi/local/share/info/dir \
		/home/javi/local/share/info/readline.info ; \
	install-info --dir-file=/home/javi/local/share/info/dir \
		/home/javi/local/share/info/history.info ; \
	install-info --dir-file=/home/javi/local/share/info/dir \
		/home/javi/local/share/info/rluserman.info ; \
else true; fi
/usr/bin/install -c -m 644 ./readline.3 /home/javi/local/share/man/man3/readline.3
/usr/bin/install -c -m 644 ./history.3 /home/javi/local/share/man/man3/history.3
if test -n "" ; then \
	if test -f readline.html; then \
		/usr/bin/install -c -m 644 readline.html /readline.html; \
	else \
		/usr/bin/install -c -m 644 ./readline.html /readline.html; \
	fi ; \
	if test -f history.html; then \
		/usr/bin/install -c -m 644 history.html /history.html; \
	else \
		/usr/bin/install -c -m 644 ./history.html /history.html; \
	fi ; \
	if test -f rluserman.html; then \
		/usr/bin/install -c -m 644 rluserman.html /rluserman.html; \
	else \
		/usr/bin/install -c -m 644 ./rluserman.html /rluserman.html; \
	fi ; \
fi
make[1]: se sale del directorio '/home/javi/athame/readline-7.0_tmp/doc'
( cd examples ; make  DESTDIR= install )
make[1]: se entra en el directorio '/home/javi/athame/readline-7.0_tmp/examples'
/bin/sh ../support/mkdirs /home/javi/local/share/readline
mkdir /home/javi/local/share/readline
make[1]: se sale del directorio '/home/javi/athame/readline-7.0_tmp/examples'
rm -f /home/javi/local/lib/athame_readline/vimbed.vim && rm -f -r /home/javi/local/lib/athame_readline
cp -r ./vimbed/plugin /home/javi/local/lib/athame_readline
mv /home/javi/local/lib/libreadline.a /home/javi/local/lib/libreadline.old
mv: no se puede efectuar `stat' sobre '/home/javi/local/lib/libreadline.a': *No existe el fichero o el directorio*
make: [Makefile:243: install-static] Error 1 (no tiene efecto)
/usr/bin/install -c -m 644 libreadline.a /home/javi/local/lib/libreadline.a
test -n "ranlib" && ranlib /home/javi/local/lib/libreadline.a
mv /home/javi/local/lib/libhistory.a /home/javi/local/lib/libhistory.old
mv: no se puede efectuar `stat' sobre '/home/javi/local/lib/libhistory.a': No existe el fichero o el directorio
make: [Makefile:246: install-static] Error 1 (no tiene efecto)
/usr/bin/install -c -m 644 libhistory.a /home/javi/local/lib/libhistory.a
```

It would be useful can use "C-x C-l" to line completion, and having an copy-paste mode

**Comment by ardagnir** [comment] 2018-06-12 05:32
Hmm, that's weird. But it still works? It's just the static-install that fails?
What do you get for ls in ~/local/lib/ ?

I'm not sure what you mean by copy-paste mode, but you can still use C-xC-l(without the dropdown menu) as long as you don't use the default readline config that uses C-l to clear. (Athame gives some readline commands, like clear, precedence instead of sending them to Vim. You can edit which keys, if any, control these commands in the .inputrc the normal readline way.)

**Comment by i5513** [comment] 2018-06-15 22:03
> Hmm, that's weird. But it still works? It's just the static-install that fails?

Yes , it work

>  What do you get for ls in ~/local/lib/ ?

$ ls ~/local/lib/ 
athame_readline  libhistory.a   libhistory.so.7    libreadline.a   libreadline.so.7    pkgconfig
bash             libhistory.so  libhistory.so.7.0  libreadline.so  libreadline.so.7.0

> I'm not sure what you mean by copy-paste mode, 
I refer, selecting text and copy it to clipboard, and then paste. But i know, it is more to be done at terminal level (like termite)

> but you can still use C-xC-l(without the dropdown menu) as long as you don't use the default readline config that uses C-l to clear.

bind -u clear-screen did the trick , thanks !

**Comment by ardagnir** [comment] 2018-06-16 21:51
I got confused. This is just the error from the readline installer trying to remove the old version and failing. It’s not caused by Athame.

You can copy/paste athame text with the clipboard using “+ or “* If you mean the output text, that is never sent to readline, so you’re right about needing to do that at the terminal level.

**Closed by ardagnir** 2018-06-16 21:51 UTC
